// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------------- //
// rp2350_iocs16 //
// ------------- //

#define rp2350_iocs16_wrap_target 1
#define rp2350_iocs16_wrap 3
#define rp2350_iocs16_pio_version 1

static const uint16_t rp2350_iocs16_program_instructions[] = {
    0xe001, //  0: set    pins, 1                    
            //     .wrap_target
    0x6028, //  1: out    x, 8                       
    0x00a0, //  2: jmp    x != y, 0                  
    0xe000, //  3: set    pins, 0                    
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program rp2350_iocs16_program = {
    .instructions = rp2350_iocs16_program_instructions,
    .length = 4,
    .origin = -1,
    .pio_version = rp2350_iocs16_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config rp2350_iocs16_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + rp2350_iocs16_wrap_target, offset + rp2350_iocs16_wrap);
    sm_config_set_out_pin_count(&c, 0);
    sm_config_set_out_shift(&c, 1, 1, 8);
    return c;
}
#endif

