// Standard values for IDE protocol
#pragma once

// Status register bits
#define IDE_STATUS_BSY      0x80
#define IDE_STATUS_DEVRDY   0x40
#define IDE_STATUS_DEVFAULT 0x20
#define IDE_STATUS_DATAREQ  0x08
#define IDE_STATUS_ERR      0x01

// Error register bits
// Note that these vary by command type
#define IDE_ERROR_WRITEPROTECT    0x40
#define IDE_ERROR_MEDIACHANGE     0x20
#define IDE_ERROR_MEDIACHANGEREQ  0x08
#define IDE_ERROR_ABORT           0x04
#define IDE_ERROR_NOMEDIA         0x01

// IDE command set
#define IDE_CMD_NOP                                       0x00
#define IDE_CMD_CFA_REQUEST_EXTENDED_ERROR                0x03
#define IDE_CMD_DEVICE_RESET                              0x08
#define IDE_CMD_READ_SECTORS                              0x20
#define IDE_CMD_READ_SECTORS_EXT                          0x24
#define IDE_CMD_READ_DMA_EXT                              0x25
#define IDE_CMD_READ_DMA_QUEUED_EXT                       0x26
#define IDE_CMD_READ_NATIVE_MAX_ADDRESS_EXT               0x27
#define IDE_CMD_READ_MULTIPLE_EXT                         0x29
#define IDE_CMD_READ_LOG_EXT                              0x2F
#define IDE_CMD_WRITE_SECTORS                             0x30
#define IDE_CMD_WRITE_SECTORS_EXT                         0x34
#define IDE_CMD_WRITE_DMA_EXT                             0x35
#define IDE_CMD_WRITE_DMA_QUEUED_EXT                      0x36
#define IDE_CMD_SET_MAX_ADDRESS_EXT                       0x37
#define IDE_CMD_CFA_WRITE_SECTORS_WOUT_ERASE              0x38
#define IDE_CMD_WRITE_MULTIPLE_EXT                        0x39
#define IDE_CMD_WRITE_LOG_EXT                             0x3F
#define IDE_CMD_READ_VERIFY_SECTORS                       0x40
#define IDE_CMD_READ_VERIFY_SECTORS_EXT                   0x42
#define IDE_CMD_SEEK                                      0x70
#define IDE_CMD_CFA_TRANSLATE_SECTOR                      0x87
#define IDE_CMD_EXECUTE_DEVICE_DIAGNOSTIC                 0x90
#define IDE_CMD_DOWNLOAD_MICROCODE                        0x92
#define IDE_CMD_PACKET                                    0xA0
#define IDE_CMD_IDENTIFY_PACKET_DEVICE                    0xA1
#define IDE_CMD_SERVICE                                   0xA2
#define IDE_CMD_SMART                                     0xB0
#define IDE_CMD_DEVICE_CONFIGURATION                      0xB1
#define IDE_CMD_CFA_ERASE_SECTORS                         0xC0
#define IDE_CMD_READ_MULTIPLE                             0xC4
#define IDE_CMD_WRITE_MULTIPLE                            0xC5
#define IDE_CMD_SET_MULTIPLE_MODE                         0xC6
#define IDE_CMD_READ_DMA_QUEUED                           0xC7
#define IDE_CMD_READ_DMA                                  0xC8
#define IDE_CMD_WRITE_DMA                                 0xCA
#define IDE_CMD_WRITE_DMA_QUEUED                          0xCC
#define IDE_CMD_CFA_WRITE_MULTIPLE_WOUT_ERASE             0xCD
#define IDE_CMD_CHECK_MEDIA_CARD_TYPE                     0xD1
#define IDE_CMD_GET_MEDIA_STATUS                          0xDA
#define IDE_CMD_MEDIA_LOCK                                0xDE
#define IDE_CMD_MEDIA_UNLOCK                              0xDF
#define IDE_CMD_STANDBY_IMMEDIATE                         0xE0
#define IDE_CMD_IDLE_IMMEDIATE                            0xE1
#define IDE_CMD_STANDBY                                   0xE2
#define IDE_CMD_IDLE                                      0xE3
#define IDE_CMD_READ_BUFFER                               0xE4
#define IDE_CMD_CHECK_POWER_MODE                          0xE5
#define IDE_CMD_SLEEP                                     0xE6
#define IDE_CMD_FLUSH_CACHE                               0xE7
#define IDE_CMD_WRITE_BUFFER                              0xE8
#define IDE_CMD_FLUSH_CACHE_EXT                           0xEA
#define IDE_CMD_IDENTIFY_DEVICE                           0xEC
#define IDE_CMD_MEDIA_EJECT                               0xED
#define IDE_CMD_SET_FEATURES                              0xEF
#define IDE_CMD_SECURITY_SET_PASSWORD                     0xF1
#define IDE_CMD_SECURITY_UNLOCK                           0xF2
#define IDE_CMD_SECURITY_ERASE_PREPARE                    0xF3
#define IDE_CMD_SECURITY_ERASE_UNIT                       0xF4
#define IDE_CMD_SECURITY_FREEZE_LOCK                      0xF5
#define IDE_CMD_SECURITY_DISABLE_PASSWORD                 0xF6
#define IDE_CMD_READ_NATIVE_MAX_ADDRESS                   0xF8
#define IDE_CMD_SET_MAX_ADDRESS                           0xF9

// X-macro list of the command names, for use with e.g. debug printers.
#define IDE_COMMAND_LIST(X) \
X(NOP                             ) \
X(CFA_REQUEST_EXTENDED_ERROR      ) \
X(DEVICE_RESET                    ) \
X(READ_SECTORS                    ) \
X(READ_SECTORS_EXT                ) \
X(READ_DMA_EXT                    ) \
X(READ_DMA_QUEUED_EXT             ) \
X(READ_NATIVE_MAX_ADDRESS_EXT     ) \
X(READ_MULTIPLE_EXT               ) \
X(READ_LOG_EXT                    ) \
X(WRITE_SECTORS                   ) \
X(WRITE_SECTORS_EXT               ) \
X(WRITE_DMA_EXT                   ) \
X(WRITE_DMA_QUEUED_EXT            ) \
X(SET_MAX_ADDRESS_EXT             ) \
X(CFA_WRITE_SECTORS_WOUT_ERASE    ) \
X(WRITE_MULTIPLE_EXT              ) \
X(WRITE_LOG_EXT                   ) \
X(READ_VERIFY_SECTORS             ) \
X(READ_VERIFY_SECTORS_EXT         ) \
X(SEEK                            ) \
X(CFA_TRANSLATE_SECTOR            ) \
X(EXECUTE_DEVICE_DIAGNOSTIC       ) \
X(DOWNLOAD_MICROCODE              ) \
X(PACKET                          ) \
X(IDENTIFY_PACKET_DEVICE          ) \
X(SERVICE                         ) \
X(SMART                           ) \
X(DEVICE_CONFIGURATION            ) \
X(CFA_ERASE_SECTORS               ) \
X(READ_MULTIPLE                   ) \
X(WRITE_MULTIPLE                  ) \
X(SET_MULTIPLE_MODE               ) \
X(READ_DMA_QUEUED                 ) \
X(READ_DMA                        ) \
X(WRITE_DMA                       ) \
X(WRITE_DMA_QUEUED                ) \
X(CFA_WRITE_MULTIPLE_WOUT_ERASE   ) \
X(CHECK_MEDIA_CARD_TYPE           ) \
X(GET_MEDIA_STATUS                ) \
X(MEDIA_LOCK                      ) \
X(MEDIA_UNLOCK                    ) \
X(STANDBY_IMMEDIATE               ) \
X(IDLE_IMMEDIATE                  ) \
X(STANDBY                         ) \
X(IDLE                            ) \
X(READ_BUFFER                     ) \
X(CHECK_POWER_MODE                ) \
X(SLEEP                           ) \
X(FLUSH_CACHE                     ) \
X(WRITE_BUFFER                    ) \
X(FLUSH_CACHE_EXT                 ) \
X(IDENTIFY_DEVICE                 ) \
X(MEDIA_EJECT                     ) \
X(SET_FEATURES                    ) \
X(SECURITY_SET_PASSWORD           ) \
X(SECURITY_UNLOCK                 ) \
X(SECURITY_ERASE_PREPARE          ) \
X(SECURITY_ERASE_UNIT             ) \
X(SECURITY_FREEZE_LOCK            ) \
X(SECURITY_DISABLE_PASSWORD       ) \
X(READ_NATIVE_MAX_ADDRESS         ) \
X(SET_MAX_ADDRESS                 )
